const cities = [
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
  'Berkeley',
  'Beverly Hills',
  'Big Bear Lake',
  'Biggs',
  'Bishop',
  'Blue Lake',
  'Blythe',
  'Bradbury',
  'Brawley',
  'Brea',
  'Brentwood',
  'Brisbane',
  'Buellton',
  'Buena Park',
  'Burbank',
  'Burlingame',
  'Calabasas',
  'Calexico',
  'California City',
  'Calimesa',
  'Calipatria',
  'Calistoga',
  'Camarillo',
  'Campbell',
  'Canyon Lake',
  'Capitola',
  'Carlsbad',
  'Carmel-by-the-Sea',
  'Carpinteria',
  'Carson',
  'Cathedral City',
  'Ceres',
  'Cerritos',
  'Chico',
  'Chino',
  'Chino Hills',
  'Chowchilla',
  'Chula Vista',
  'Citrus Heights',
  'Claremont',
  'Clayton',
  'Clearlake',
  'Cloverdale',
  'Clovis',
  'Coachella',
  'Coalinga',
  'Colfax',
  'Colma',
  'Colton',
  'Colusa',
  'Commerce',
  'Compton',
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
  'Berkeley',
  'Beverly Hills',
  'Big Bear Lake',
  'Biggs',
  'Bishop',
  'Blue Lake',
  'Blythe',
  'Bradbury',
  'Brawley',
  'Brea',
  'Brentwood',
  'Brisbane',
  'Buellton',
  'Buena Park',
  'Burbank',
  'Burlingame',
  'Calabasas',
  'Calexico',
  'California City',
  'Calimesa',
  'Calipatria',
  'Calistoga',
  'Camarillo',
  'Campbell',
  'Canyon Lake',
  'Capitola',
  'Carlsbad',
  'Carmel-by-the-Sea',
  'Carpinteria',
  'Carson',
  'Cathedral City',
  'Ceres',
  'Cerritos',
  'Chico',
  'Chino',
  'Chino Hills',
  'Chowchilla',
  'Chula Vista',
  'Citrus Heights',
  'Claremont',
  'Clayton',
  'Clearlake',
  'Cloverdale',
  'Clovis',
  'Coachella',
  'Coalinga',
  'Colfax',
  'Colma',
  'Colton',
  'Colusa',
  'Commerce',
  'Compton',
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
  'Berkeley',
  'Beverly Hills',
  'Big Bear Lake',
  'Biggs',
  'Bishop',
  'Blue Lake',
  'Blythe',
  'Bradbury',
  'Brawley',
  'Brea',
  'Brentwood',
  'Brisbane',
  'Buellton',
  'Buena Park',
  'Burbank',
  'Burlingame',
  'Calabasas',
  'Calexico',
  'California City',
  'Calimesa',
  'Calipatria',
  'Calistoga',
  'Camarillo',
  'Campbell',
  'Canyon Lake',
  'Capitola',
  'Carlsbad',
  'Carmel-by-the-Sea',
  'Carpinteria',
  'Carson',
  'Cathedral City',
  'Ceres',
  'Cerritos',
  'Chico',
  'Chino',
  'Chino Hills',
  'Chowchilla',
  'Chula Vista',
  'Citrus Heights',
  'Claremont',
  'Clayton',
  'Clearlake',
  'Cloverdale',
  'Clovis',
  'Coachella',
  'Coalinga',
  'Colfax',
  'Colma',
  'Colton',
  'Colusa',
  'Commerce',
  'Compton',
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
  'Berkeley',
  'Beverly Hills',
  'Big Bear Lake',
  'Biggs',
  'Bishop',
  'Blue Lake',
  'Blythe',
  'Bradbury',
  'Brawley',
  'Brea',
  'Brentwood',
  'Brisbane',
  'Buellton',
  'Buena Park',
  'Burbank',
  'Burlingame',
  'Calabasas',
  'Calexico',
  'California City',
  'Calimesa',
  'Calipatria',
  'Calistoga',
  'Camarillo',
  'Campbell',
  'Canyon Lake',
  'Capitola',
  'Carlsbad',
  'Carmel-by-the-Sea',
  'Carpinteria',
  'Carson',
  'Cathedral City',
  'Ceres',
  'Cerritos',
  'Chico',
  'Chino',
  'Chino Hills',
  'Chowchilla',
  'Chula Vista',
  'Citrus Heights',
  'Claremont',
  'Clayton',
  'Clearlake',
  'Cloverdale',
  'Clovis',
  'Coachella',
  'Coalinga',
  'Colfax',
  'Colma',
  'Colton',
  'Colusa',
  'Commerce',
  'Compton',
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
  'Berkeley',
  'Beverly Hills',
  'Big Bear Lake',
  'Biggs',
  'Bishop',
  'Blue Lake',
  'Blythe',
  'Bradbury',
  'Brawley',
  'Brea',
  'Brentwood',
  'Brisbane',
  'Buellton',
  'Buena Park',
  'Burbank',
  'Burlingame',
  'Calabasas',
  'Calexico',
  'California City',
  'Calimesa',
  'Calipatria',
  'Calistoga',
  'Camarillo',
  'Campbell',
  'Canyon Lake',
  'Capitola',
  'Carlsbad',
  'Carmel-by-the-Sea',
  'Carpinteria',
  'Carson',
  'Cathedral City',
  'Ceres',
  'Cerritos',
  'Chico',
  'Chino',
  'Chino Hills',
  'Chowchilla',
  'Chula Vista',
  'Citrus Heights',
  'Claremont',
  'Clayton',
  'Clearlake',
  'Cloverdale',
  'Clovis',
  'Coachella',
  'Coalinga',
  'Colfax',
  'Colma',
  'Colton',
  'Colusa',
  'Commerce',
  'Compton',
  'Adelanto',
  'Agoura Hills',
  'Alameda',
  'Albany',
  'Alhambra',
  'Aliso Viejo',
  'Alturas',
  'Amador City',
  'American Canyon',
  'Anaheim',
  'Anderson',
  'Angels Camp',
  'Antioch',
  'Apple Valley',
  'Arcadia',
  'Arcata',
  'Arroyo Grande',
  'Artesia',
  'Arvin',
  'Atascadero',
  'Atherton',
  'Atwater',
  'Auburn',
  'Avalon',
  'Avenal',
  'Azusa',
  'Bakersfield',
  'Baldwin Park',
  'Banning',
  'Barstow',
  'Beaumont',
  'Bell',
  'Bell Gardens',
  'Bellflower',
  'Belmont',
  'Belvedere',
  'Benicia',
];

module.exports = cities;
